use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum GovernanceError {
    AlreadyInitialized = 1,
    NotInitialized = 2,
    Unauthorized = 3,
    InvalidSupply = 4,
    InvalidAmount = 5,
    InvalidDuration = 6,
    DuplicateSchedule = 7,
    VestingScheduleNotFound = 8,
    CliffNotReached = 9,
    NothingToRelease = 10,
    InsufficientBalance = 11,
    InsufficientStakedBalance = 12,
    ActiveVoteLock = 13,
    BelowMinimumClaim = 14,
    LiquidityPoolExhausted = 15,
    DuplicateRecipient = 16,
    ArithmeticOverflow = 17,
    InvalidRewardConfig = 18,
    InvalidMetadata = 19,
    BudgetNotFound = 20,
    BudgetExceeded = 21,
    BudgetPeriodEnded = 22,
    MissingAssetPrice = 23,
    InvalidTreasuryConfig = 24,
    InvalidCommitteeConfig = 25,
    CommitteeNotFound = 26,
    CommitteeTermEnded = 27,
    CommitteeDecisionNotFound = 28,
    CommitteeDecisionNotOpen = 29,
    AlreadyVoted = 30,
    NoCommitteeAuthority = 31,
    CommitteeElectionNotFound = 32,
    CommitteeElectionNotActive = 33,
    NotCommitteeCandidate = 34,
    CrossCommitteeRequestNotFound = 35,
    CommitteeInactive = 36,
    InvalidCommitteeAction = 37,
    InvalidApprovalRating = 38,
}
